language: c
before_script:
  - autoreconf -if
script:
  - ./configure --prefix=/usr
  - make -k
  - make check
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - libcryptsetup-dev
      - libssl-dev
