sudo: required

language: c

services:
  - docker

compiler:
  - gcc

env:
  - DISTRO=fedora:rawhide
  - DISTRO=fedora:25
  - DISTRO=fedora:24
  - DISTRO=centos:7

script:
  - >
    docker run
    -v `pwd`:/tmp/build
    -w /tmp/build
    -e CC=$CC
    $DISTRO /bin/bash -ex .travis.test $DISTRO
