---
name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        os:
          - fedora:rawhide
          - fedora:latest
          - centos:7
          - centos:8
          - debian:testing
          - debian:latest
          - debian:stable-slim
          - ubuntu:devel
          - ubuntu:rolling
          - ubuntu:bionic
          - ubuntu:focal #20.04 LTS
    steps:
      - uses: actions/checkout@v3

      - name: Show OS information
        run: cat /etc/os-release 2>/dev/null || echo /etc/os-release not available

      - name: Install build dependencies
        run: sh .github/workflows/install-dependencies

      - name: Build tang
        run: |
          mkdir -p build && cd build
          export ninja=$(command -v ninja)
          [ -z "${ninja}" ] && export ninja=$(command -v ninja-build)
          meson .. || cat meson-logs/meson-log.txt >&2
          ${ninja}

      - name: Run tests
        run: |
          cd build
          if ! meson test ; then
              cat meson-logs/testlog.txt >&2
              exit -1
          fi

      - name: Show full test logs
        run: |
          if [ -r build/meson-logs/testlog.txt ]; then
            cat build/meson-logs/testlog.txt >&2
          else
            echo "No test log available" >&2
          fi

    container:
      image: ${{matrix.os}}
      env:
        DISTRO: ${{matrix.os}}

# vim:set ts=2 sw=2 et:
