#!/bin/sh -ex
SKIP_ADDITIONAL_PACKAGES=${SKIP_ADDITIONAL_PACKAGES:-"no"} # default no skip

case "${DISTRO}" in
debian:*|ubuntu:*)
    export DEBIAN_FRONTEND=noninteractive
    apt update
    apt -y --no-install-recommends install jose socat libhttp-parser-dev curl 
    [ "$SKIP_ADDITIONAL_PACKAGES" = "no" ] && apt -y install gcc meson pkg-config libjose-dev jose libhttp-parser-dev \
                   systemd gcovr curl socat
    apt -y clean
    rm -r /var/lib/apt/lists/*
    ;;

fedora:*)
    echo 'max_parallel_downloads=10' >> /etc/dnf/dnf.conf
    dnf -y clean all
    dnf -y --setopt=deltarpm=0 update
    dnf -y install gcc meson pkgconfig libjose-devel jose http-parser-devel \
                   systemd gcovr curl socat
    ;;

centos:*)
    yum -y clean all
    yum -y --setopt=deltarpm=0 update
    yum install -y yum-utils epel-release
    yum config-manager -y --set-enabled PowerTools \
        || yum config-manager -y --set-enabled powertools || :
    yum -y install meson socat
    yum-builddep -y tang
    ;;
esac
# vim: set ts=8 shiftwidth=4 softtabstop=4 expandtab smarttab colorcolumn=80:
